
name: Ubuntu x64

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*'  # Trigger on "version" tags
  pull_request: # Trigger on PRs from any branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make Mochimo Install
        run: make mochimo -C ${{ github.workspace }}
