
name: MacOS 15 (arm64)
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make Mochimo Install
        run: make mochimo -C ${{ github.workspace }}
